import {Bath,BedDouble,Building2,Check,ChevronLeft,Heart,MapPin,Phone} from "lucide-react";
import {Link,useParams} from "react-router-dom";
import {formatPrice} from "../data/properties";

export default function PropertyPage({properties,favourites,toggle}){
  const {id}=useParams();
  const p=properties.find(x=>x.id===+id);
  if(!p)return <div className="container py-24 text-center"><h1 className="text-3xl font-bold">Property not found</h1></div>;
  const saved=favourites.includes(p.id);
  const whatsappLink = `https://wa.me/15551234567?text=${encodeURIComponent(`Hello GreenGate Property, I would like to arrange a viewing for ${p.title} in ${p.location}.`)}`;
  return <main className="container py-8"><Link to="/properties" className="mb-6 flex items-center gap-2 font-semibold text-slate-500"><ChevronLeft size={18}/>Back to results</Link><div className="grid h-[500px] gap-3 overflow-hidden rounded-3xl md:grid-cols-[1.8fr_1fr] md:grid-rows-2"><img src={p.gallery[0]} alt={p.title} className="h-full w-full object-cover md:row-span-2"/><img src={p.gallery[1]||p.image} alt="" className="hidden h-full w-full object-cover md:block"/><img src={p.gallery[2]||p.image} alt="" className="hidden h-full w-full object-cover md:block"/></div><div className="grid gap-10 py-10 lg:grid-cols-[1fr_380px]"><div><div className="flex justify-between gap-4"><div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700">FOR SALE</span><h1 className="mt-4 text-4xl font-bold">{p.title}</h1><p className="mt-2 flex gap-2 text-slate-500"><MapPin size={18}/>{p.location}</p></div><button onClick={()=>toggle(p.id)} className="flex h-fit items-center gap-2 rounded-xl border px-4 py-3 font-bold"><Heart className={saved?"fill-rose-500 text-rose-500":""}/>{saved?"Saved":"Save"}</button></div><div className="my-8 flex flex-wrap gap-8 border-y py-5"><b className="text-3xl">{formatPrice(p.price)}</b><span className="flex gap-2"><BedDouble className="text-emerald-700"/>{p.beds} bedrooms</span><span className="flex gap-2"><Bath className="text-emerald-700"/>{p.baths} bathrooms</span><span className="flex gap-2"><Building2 className="text-emerald-700"/>{p.type}</span></div><h2 className="text-2xl font-bold">About this home</h2><p className="mt-4 text-lg leading-8 text-slate-600">{p.description}</p><h2 className="mt-10 text-2xl font-bold">Key features</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{p.features&&p.features.map(f=><div key={f} className="flex items-center gap-3 rounded-xl bg-slate-50 p-4"><Check className="text-emerald-700" size={18}/><span>{f}</span></div>)}</div></div><aside className="self-start rounded-2xl border border-emerald-100 bg-emerald-50 p-4 shadow-sm"><div className="rounded-xl bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-emerald-700">Property owner</p><h3 className="mt-2 text-xl font-bold text-slate-900">Adele Finch</h3><p className="mt-1 text-sm text-slate-600">Trusted property advisor</p><div className="mt-4 space-y-2 text-sm text-slate-700"><div className="flex items-center gap-2"><Phone className="text-emerald-700" size={16}/><span>+44 20 7946 0957</span></div><div className="flex items-center gap-2"><MapPin className="text-emerald-700" size={16}/><span>{p.location}</span></div></div></div><a href={whatsappLink} target="_blank" rel="noreferrer" className="btn-primary mt-4 block w-full text-center">Arrange a viewing</a></aside></div></main>;
}
